#!/usr/bin/env bash
#Display a list of currently running processe.
#Show all processes, for all user, including those
#which might not have a TTY.
#Display in a user-oriented format
#Shows process hierarchy

ps -auxf
