#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100 in list format.
#displays FizzBuzz when the number is a multiple of 3 and 5.
#displays Fizz when the number is a multiple of 3.
#displays Buzz when the number is a multiple of 5.
#Otherwise, displays the number.

for numb in {1..100}
do
  if (( numb % 3 == 0 && numb % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( numb % 3 == 0 ))
  then
    echo "Fizz"
  elif (( numb % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$numb"
  fi
done
