#!/usr/bin/env bash
#display a  Parsed the Apache log files in list format.
#bash script Groups visitors by IP and HTTP status code.
#bsh script Displays the number of occurrences, IP, and HTTP status
#+code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn

