#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 in addition and:
#display"bad luck from China" for the 4th iteration
#display"bad luck from Japan" for the 9th iteration
#display"bad luck from Italy" for the 17th loop iteration

cnt=1

while [ $cnt -le 20 ]
do
  echo "$cnt"
  case $cnt in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( cnt++ ))
done

