#!/usr/bin/env bash
#Bash script that displays the time for 12 horus and 59 minutes.
#displays hours from 0 to 12
#displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minutes=1
  while [ $minutes -le 59 ]
  do
    echo "$minutes"
    (( minutes++ ))
  done
  (( hour++ ))
done
